{
  pkgs,
  inputs,
  ...
}: {
  home.packages = with pkgs; [
    eloquent
    file-roller
    foliate
    gearlever
    inputs.zen-browser.packages.${pkgs.stdenv.hostPlatform.system}.default
    localsend
    nextcloud-client
    onlyoffice-desktopeditors
    pdfarranger
    python314Packages.deemix
    postman
    trayscale
    vesktop
    zathura
    standardnotes
    pandoc
    tectonic
    librsvg
    xournalpp
    protonplus
    cartridges
    ryubing
    supertuxkart
    bustle
    cutter
    #gaphor
    learn6502
    kdePackages.merkuro
    qtrvsim
    rustlings
    element-desktop
    morgen
  ];
}
