# The laptop host, as one unit.
#
# Split into four files so each has a single job:
#
#   default.nix               imports the rest, and marks this host as
#                             nixarchy's own
#   configuration.nix          system-level
#   home.nix                   Home Manager
#   hardware-configuration.nix generated by nixos-generate-config, untouched
#
# The hostname is "nixos" and this directory is hosts/nixos. nixarchy-apply
# derives its target directory from `uname -n` and will not find hosts/mfv3.
{ inputs, ... }:

{
  imports = [
    ./configuration.nix
    # home.nix is deliberately NOT here. It is a Home Manager module and is
    # imported by flake.nix through `home-manager.users.mark`. Listing it in a
    # NixOS module list evaluates it against the system option set, where
    # `home` does not exist.
  ];

  # installerManaged is deliberately NOT set to true here, though it was on an
  # earlier draft of this file. The option's own description is the reason:
  #
  #   "Whether this configuration descends from the host module the Nixarchy
  #    installer generates. Set by installer/host.nix and by nothing else."
  #
  # True writes /etc/nixarchy/managed, which is the single predicate that arms
  # nixarchy's auto-commit, auto-push and config-rewrite commands. Claiming it
  # here would let those rewrite the configuration unprompted on a machine the
  # installer never wrote. The live system has it false, so false it stays --
  # hosts/nixos/configuration.nix sets it explicitly to document that.

  # Where nixarchy-apply copies the app selection before rebuilding.
  programs.nixarchy.flake = "/etc/nixos";
}