config_version = 14

[bar.default]
background_opacity = 0.84999998100101948
center = [ "clock", "media", "bar_2" ]
color = "primary"
end = [ "tray", "notifications", "clipboard", "network", "bluetooth", "battery", "session" ]
margin_edge = 10
margin_ends = 17
radius = 0
start = [ "workspaces" ]

[control_center]
width = 1050

[lockscreen_widgets]
enabled = false
schema_version = 2
widget_order = [ "lockscreen-login-box@DP-3", "lockscreen-login-box@eDP-1" ]

    [lockscreen_widgets.grid]
    cell_size = 16
    major_interval = 4
    visible = true

    [lockscreen_widgets.widget."lockscreen-login-box@DP-3"]
    box_height = 196.0
    box_width = 810.0
    cx = 960.0
    cy = 898.0
    output = "DP-3"
    placement_height = 1080.0
    placement_width = 1920.0
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@DP-3".settings]
        background_color = "surface_variant"
        background_opacity = 0.88
        background_radius = 12.0
        center_password_text = false
        input_opacity = 1.0
        input_radius = 6.0
        layout = "regular"
        show_caps_lock = true
        show_keyboard_layout = true
        show_login_button = true
        show_media = true
        show_session_buttons = true
        show_unlock_hint = true
        show_weather = true

    [lockscreen_widgets.widget."lockscreen-login-box@eDP-1"]
    box_height = 196.0
    box_width = 810.0
    cx = 854.0
    cy = 885.0
    output = "eDP-1"
    placement_height = 1067.0
    placement_width = 1707.0
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@eDP-1".settings]
        background_color = "surface_variant"
        background_opacity = 0.88
        background_radius = 12.0
        center_password_text = false
        input_opacity = 1.0
        input_radius = 6.0
        layout = "regular"
        show_caps_lock = true
        show_keyboard_layout = true
        show_login_button = true
        show_media = true
        show_session_buttons = true
        show_unlock_hint = true
        show_weather = true

[plugins]
enabled = [
    "yuuto/calculator",
    "kenn/keybind-cheatsheet",
    "avivbintangaringga/nix-monitor",
    "knyrps/nix-search",
    "mindnbytes/nix-status",
    "fel/podcasts",
    "raycursive/niri-displays"
]

[shell]
font_family = "Inter"
screen_time_enabled = true

    [shell.panel]
    control_center_placement = "floating"
    session_placement = "floating"
    transparency_mode = "soft"

    [shell.screenshot]
    confirm_region = true
    remember_last_region = true

[theme]
builtin = "Gruvbox"
source = "wallpaper"

    [theme.templates]
    community_ids = [
        "antigravity",
        "opencode",
        "spicetify",
        "pywalfox",
        "ungoogled-chromium",
        "discord",
        "micro",
        "neovim",
        "zed",
        "heroiclauncher",
        "steam",
        "fuzzel",
        "fastfetch",
        "thunderbird",
        "zathura",
        "papirus-icons",
        "bat",
        "fzf",
        "lazygit",
        "tmux",
        "yazi"
    ]

[wallpaper]
directory = "/home/mark/Pictures/wallpaper"

    [wallpaper.default]
    path = "/home/mark/Pictures/wallpaper/1-the-backwater.jpg"

    [wallpaper.last]
    path = "/home/mark/Pictures/wallpaper/1-the-backwater.jpg"

[widget.bar_2]
show_name = false
type = "fel/podcasts:bar"

[widget.battery]
display_mode = "graphic"
show_label = false

[widget.bluetooth]
hide_when_no_connected_device = true

[widget.media]
hide_when_no_media = true
show_progress = true

[widget.network]
show_label = false

[widget.notifications]
hide_when_no_unread = true

[widget.tray]
drawer = true