[General]
AdmsXmlBinDir=
AllowFlexibleWires=false
AppStyle=Fusion
AscoBinDir=
Attribute=#afcfab
BGColor=#eae1d4
Character=#ffb4ab
Comment=#999080
DefaultSimulator=1
Directive=#e7c26c
Editor=qucs
FileTypes=@Invalid()
GraphAntiAliasing=false
GridColor=#999080
IgnoreVersion=false
Integer=#d7c5a0
Language=
LargeFontSize=16
MainWindowGeometry=@ByteArray(\x1\xd9\xd0\xcb\0\x3\0\0\0\0\0\0\0\0\0\0\0\0\x6\x8a\0\0\x3\xe0\0\0\0\0\0\0\0\0\0\0\x6\x8a\0\0\x3\xe0\0\0\0\0\0\0\0\0\x6\xab\0\0\0\0\0\0\0\0\0\0\x6\x8a\0\0\x3\xe0)
NgspiceExecutable=/usr/bin/ngspice
NodeWiring=1
Nprocs=4
OctaveExecutable=octave
OpenVAFExecutable=
QucsHomeDir=/home/mark/QucsWorkspace
Qucsator=/usr/bin/qucsator_rf
Real=#e7c26c
RecentDocs=/home/mark/Nextcloud/Documents/School/2026 - Fall/Active Circuits/Labs/Lab03.sch*/home/mark/Nextcloud/Documents/School/2026 - Fall/Active Circuits/Labs/Lab02.2.sch*/home/mark/Nextcloud/Documents/School/2026 - Fall/Active Circuits/Assignments/Assignment1_Circiuts2.sch*/home/mark/Nextcloud/Documents/School/2026 - Fall/Active Circuits/Assignments/Assignment1_Circiuts.sch*/home/mark/Nextcloud/Documents/School/2026 - Fall/Active Circuits/Labs/Lab02.1.sch
S4Q_workdir=/home/mark/.cache/qucs-s
SpiceOpusExecutable=spiceopus
String=#afcfab
Task=#ffb4ab
TextAntiAliasing=false
Type=#d7c5a0
XyceExecutable=/usr/local/Xyce-Release-6.8.0-OPENSOURCE/bin/Xyce
XyceParExecutable=mpirun -np %p /usr/local/Xyce-Release-6.8.0-OPENMPI-OPENSOURCE/bin/Xyce
alwaysPrefixDataset=false
appFont="Sans Serif,9,-1,5,400,0,0,0,0,0,0,0,0,0,0,1,,0,0"
firstRun=false
font="Sans Serif,12,-1,5,400,0,0,0,0,0,0,0,0,0,0,1,,0,0"
fullTraceName=false
maxUndo=20
textFont="monospace,9,-1,2,400,0,0,0,0,0,0,0,0,0,0,1,,0,0"

[ComponentDialog]
geometry=@ByteArray(\x1\xd9\xd0\xcb\0\x3\0\0\0\0\0\0\0\0\0\0\0\0\x1Z\0\0\x1x\0\0\0\0\0\0\0\0\0\0\x1Z\0\0\x1x\0\0\0\0\0\0\0\0\x6\xab\0\0\0\0\0\0\0\0\0\0\x1Z\0\0\x1x)

[ExternSimDialog]
geometry=@ByteArray(\x1\xd9\xd0\xcb\0\x3\0\0\0\0\0\0\0\0\0\0\0\0\x1\xf3\0\0\x2\x5\0\0\0\0\0\0\0\0\0\0\x1\xf3\0\0\x2\x5\0\0\0\0\0\0\0\0\x6\xab\0\0\0\0\0\0\0\0\0\0\x1\xf3\0\0\x2\x5)

[Paths]
size=0
